### PR TITLE
Allow for DATA_URL to work

### PR DESCRIPTION
**Pull request by dgutie02**
Allow for DATA_URL to work

### CODE REVIEW

**Comment by dgutie02** [comment]
I don't have an android environment on my machine, I made all of these changes via GitHub's editor so I apologize if it doesn't compile right away. I believe though this should be all for DATA_URL option to work.

If this could be merged, and then updated on PhoneGap Build, that would be amazing.

Thanks for all your help

**Comment by grassick** [comment]
It was a little painful (there were other bugs and some of the code was Javascript-y, not Java-y), but it's there. Updating on Phonegap next...

**Comment by dgutie02** [comment]
I apologize for causing you any trouble on this merge, I'll try my best in the future to make the code more like Java rather than JS.

If you're ever in Long Island, NY send me a message I'd love to repay you for all this!

**Comment by grassick** [comment]
It's version 0.1.1... Not sure how long it will take to update on the site.

Thanks for the kind wishes!

**Comment by dgutie02** [comment]
Hey,

  Has there been any word from phonegap build? Still seems to be version 0.1.0 on their site.

Thanks,
David

**Comment by grassick** [comment]
That's odd.. it seems updating the Git repo isn't enough. And there is no
update mechanism that I can see on their site.

I've resubmitted as https://build.phonegap.com/plugins/853  It should be
live hopefully before soon

Clayton

**Comment by dgutie02** [comment]
Guessing this never went through?

**Comment by grassick** [comment]
Just checked and it's still "pending review". Adobe is painfully slow...

**Comment by dgutie02** [comment]
FYI, it seems the original plugin is now version 0.1.1. Thanks again for the help

**Pull request merged**
